# Generated by Django 4.1.11 on 2024-09-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0024_leads_lead_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_of_accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('short_code', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.chart_of_accounts')),
            ],
            options={
                'db_table': 'chart_of_accounts',
            },
        ),
        migrations.CreateModel(
            name='Journal_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=255, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('transaction_type', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('coaid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.chart_of_accounts')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'db_table': 'journal_entry',
            },
        ),
    ]
