# Generated by Django 4.1.11 on 2024-09-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart_of_accounts',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
