# Generated by Django 4.1.11 on 2024-09-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_leads_lead_type'),
        ('finance', '0003_alter_chart_of_accounts_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='coaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.chart_of_accounts'),
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project'),
        ),
    ]
