# Generated by Django 4.1.11 on 2024-09-16 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_leads_lead_type'),
        ('finance', '0004_alter_journal_entry_coaid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'payment_mode',
            },
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.bank'),
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='receive_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.payment_mode'),
        ),
    ]
