# Generated by Django 4.1.11 on 2024-10-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_leads_lead_type'),
        ('finance', '0005_payment_mode_journal_entry_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal_entry',
            name='category_type',
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='detail_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='ref_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journal_entry',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.region'),
        ),
    ]
