# Generated by Django 4.1.11 on 2024-10-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_journal_entry_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entry',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
