# Generated by Django 4.1.11 on 2024-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_account_type_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal_entry',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='conversion_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal_entry',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
