# Generated by Django 4.2.2 on 2024-12-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_journal_entry_coa_type_journal_entry_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_entry',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
