# Generated by Django 4.1.11 on 2024-02-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Company_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(null=True)),
                ('module_id', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'company_module',
            },
        ),
        migrations.CreateModel(
            name='CV_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tendor', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('templete_code', models.CharField(max_length=2000, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'cv_template',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20, null=True)),
                ('ename', models.CharField(max_length=100, null=True)),
                ('eemail', models.EmailField(max_length=254, null=True)),
                ('econtact', models.CharField(max_length=15, null=True)),
                ('cnic', models.CharField(max_length=15, null=True)),
                ('date_of_joining', models.DateField(null=True)),
                ('dob', models.DateField(null=True)),
                ('qualification_id', models.CharField(max_length=100, null=True)),
                ('deliverable_task', models.CharField(max_length=1000, null=True)),
                ('e_address', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.designation')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Mainmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField()),
                ('mainmenu_name', models.CharField(max_length=100, null=True)),
                ('mainmenu_link', models.CharField(max_length=100, null=True)),
                ('mainmenu_seq', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'mainmenu',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Role_permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.IntegerField(null=True)),
                ('mainmenu_id', models.IntegerField(null=True)),
                ('submenu_id', models.IntegerField(null=True)),
                ('role_id', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'role_permission',
            },
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainmenu_id', models.IntegerField()),
                ('submenu_name', models.CharField(max_length=100, null=True)),
                ('submenu_link', models.CharField(max_length=100, null=True)),
                ('submenu_seq', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'submenu',
            },
        ),
        migrations.CreateModel(
            name='Template_column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('table_name', models.CharField(max_length=100, null=True)),
                ('field_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'template_column',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Employement_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50, null=True)),
                ('position', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('activites', models.CharField(max_length=1000, null=True)),
                ('ref_name', models.CharField(max_length=100, null=True)),
                ('ref_email', models.EmailField(max_length=254, null=True)),
                ('ref_contact', models.CharField(max_length=15, null=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'employement_record',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.region'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=50, null=True)),
                ('institute', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('grade', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
    ]
