# Generated by Django 4.1.11 on 2023-12-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('certification_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'designation',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('degree_name', models.CharField(max_length=50)),
                ('institute', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('grade', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
                ('depart_id', models.IntegerField()),
                ('designation_id', models.IntegerField()),
                ('region_id', models.IntegerField()),
                ('cnic', models.CharField(max_length=15)),
                ('date_of_joining', models.DateField()),
                ('dob', models.DateField()),
                ('qualification_id', models.IntegerField()),
                ('deliverable_task', models.CharField(max_length=1000)),
                ('e_address', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Employement_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('organization_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('activites', models.CharField(max_length=1000)),
                ('ref_name', models.CharField(max_length=100)),
                ('ref_email', models.EmailField(max_length=254)),
                ('ref_contact', models.CharField(max_length=15)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'employement_record',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('skill_name', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
