# Generated by Django 4.1.11 on 2024-04-29 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('branch_code', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Insurance_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'insurance_type',
            },
        ),
        # migrations.RenameModel(
        #     old_name='Employement_Record',
        #     new_name='Employment_Record',
        # ),
        # migrations.AlterModelTable(
        #     name='employment_record',
        #     table='employment_record',
        # ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('advance_tax', models.IntegerField(null=True)),
                ('advance_amount', models.IntegerField(null=True)),
                ('earning_money', models.IntegerField(null=True)),
                ('instrument_no', models.IntegerField(null=True)),
                ('pg_start_date', models.DateField(null=True)),
                ('pg_end_date', models.DateField(null=True)),
                ('pg_validity', models.DateField(null=True)),
                ('pg_percentage', models.IntegerField(null=True)),
                ('pg_amount', models.IntegerField(null=True)),
                ('pg_doc', models.CharField(max_length=100, null=True)),
                ('project_doc', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Liquidity_damages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('max_percentage', models.IntegerField(null=True)),
                ('ld_doc', models.CharField(max_length=100, null=True)),
                ('addendum', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'db_table': 'liquidity_damages',
            },
        ),
        migrations.CreateModel(
            name='Insurance_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(null=True)),
                ('expire_date', models.DateField(null=True)),
                ('amount', models.IntegerField(default=1)),
                ('vendor', models.CharField(max_length=100, null=True)),
                ('instrument_no', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('insurance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.insurance_type')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'db_table': 'insurance_detail',
            },
        ),
        migrations.CreateModel(
            name='Bank_guaranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True)),
                ('instrument_no', models.IntegerField(null=True)),
                ('bg_start_date', models.DateField(null=True)),
                ('bg_end_date', models.DateField(null=True)),
                ('bg_validity', models.DateField(null=True)),
                ('bg_percentage', models.IntegerField(null=True)),
                ('bg_amount', models.IntegerField(null=True)),
                ('bg_doc', models.CharField(max_length=100, null=True)),
                ('addendum', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.bank')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'db_table': 'Bank_guaranty',
            },
        ),
    ]
