# Generated by Django 4.1.11 on 2024-04-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employment_record_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Employment_Record',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('organization_name', models.CharField(max_length=50, null=True)),
        #         ('position', models.CharField(max_length=50, null=True)),
        #         ('country', models.CharField(max_length=50, null=True)),
        #         ('from_date', models.DateField(null=True)),
        #         ('to_date', models.DateField(null=True)),
        #         ('salary', models.IntegerField(null=True)),
        #         ('activites', models.CharField(max_length=1000, null=True)),
        #         ('ref_name', models.CharField(max_length=100, null=True)),
        #         ('ref_email', models.EmailField(max_length=254, null=True)),
        #         ('ref_contact', models.CharField(max_length=15, null=True)),
        #         ('status', models.IntegerField(default=1)),
        #         ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
        #     ],
        #     options={
        #         'db_table': 'employment_record',
        #     },
        # ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'project_type',
            },
        ),
        migrations.RenameField(
            model_name='project',
            old_name='instrument_no',
            new_name='em_instrument_no',
        ),
        migrations.AddField(
            model_name='project',
            name='pg_instrument_no',
            field=models.IntegerField(null=True),
        ),
        # migrations.DeleteModel(
        #     name='Employement_Record',
        # ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project_type'),
        ),
    ]
