# Generated by Django 4.1.11 on 2024-04-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employment_record_project_type_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Employment_Record',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('organization_name', models.CharField(max_length=50, null=True)),
        #         ('position', models.CharField(max_length=50, null=True)),
        #         ('country', models.CharField(max_length=50, null=True)),
        #         ('from_date', models.DateField(null=True)),
        #         ('to_date', models.DateField(null=True)),
        #         ('salary', models.IntegerField(null=True)),
        #         ('activites', models.CharField(max_length=1000, null=True)),
        #         ('ref_name', models.CharField(max_length=100, null=True)),
        #         ('ref_email', models.EmailField(max_length=254, null=True)),
        #         ('ref_contact', models.CharField(max_length=15, null=True)),
        #         ('status', models.IntegerField(default=1)),
        #         ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
        #     ],
        #     options={
        #         'db_table': 'employment_record',
        #     },
        # ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.CharField(max_length=1000, null=True),
        ),
        # migrations.DeleteModel(
        #     name='Employement_Record',
        # ),
    ]
