# Generated by Django 4.1.11 on 2024-05-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employment_record_project_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('branch_code', models.CharField(max_length=100, null=True)),
                ('branch_address', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.area')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.country')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.region')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.zone')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
