# Generated by Django 4.1.11 on 2024-05-07 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_area_country_zone_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='region',
        ),
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.branch'),
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.branch'),
        ),
    ]
