# Generated by Django 4.1.11 on 2024-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_project_em_doc_project_em_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='em_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='pg_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
