# Generated by Django 4.1.11 on 2024-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_project_em_doc_alter_project_pg_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_guaranty',
            name='bg_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
