# Generated by Django 4.1.11 on 2024-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_liquidity_damages_ld_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='em_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pg_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
