# Generated by Django 4.1.11 on 2024-05-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_project_em_doc_alter_project_pg_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_guaranty',
            name='bg_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='liquidity_damages',
            name='ld_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
