# Generated by Django 4.1.11 on 2024-06-21 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_bank_guaranty_bg_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('deleted_at', models.DateField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'document_type',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.country'),
        ),
        migrations.AddField(
            model_name='project',
            name='em_receive_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='em_received',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='po_scan_doc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='bank_guaranty',
            table='bank_guaranty',
        ),
        migrations.CreateModel(
            name='Project_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_path', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('deleted_at', models.DateField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.document_type')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'db_table': 'project_document',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.country')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.client'),
        ),
    ]
