# Generated by Django 4.1.11 on 2024-06-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_document_type_remove_project_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_document',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
