# Generated by Django 4.1.11 on 2024-07-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_certifications_certification_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
