# Generated by Django 4.1.11 on 2024-07-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_education_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=255, null=True)),
                ('currency', models.CharField(max_length=255, null=True)),
                ('quarter_target', models.IntegerField(null=True)),
                ('year_target', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'employee_target',
            },
        ),
        migrations.CreateModel(
            name='Employee_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_key_acc_mgr', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'db_table': 'employee_project',
            },
        ),
    ]
