# Generated by Django 4.1.11 on 2024-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_employee_target_employee_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_target',
            old_name='quarter_target',
            new_name='quarter_first_target',
        ),
        migrations.AddField(
            model_name='employee_target',
            name='quarter_fourth_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee_target',
            name='quarter_second_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee_target',
            name='quarter_third_target',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='initiated_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
