# Generated by Django 4.1.11 on 2024-08-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_leads_quarters_sales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_target',
            old_name='quarter_id',
            new_name='quarter',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='lead_id',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='lead_id',
            new_name='lead',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='quarter_id',
            new_name='quarter',
        ),
    ]
