# Generated by Django 4.1.11 on 2024-08-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_rename_quarter_id_employee_target_quarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_target',
            name='sales_target',
            field=models.IntegerField(null=True),
        ),
    ]
