# Generated by Django 4.1.11 on 2024-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_project_lead_alter_sales_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
