# Generated by Django 4.1.11 on 2024-10-31 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_project_document_issuance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.country')),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
    ]
