# Generated by Django 4.1.11 on 2024-11-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0026_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='em_receive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='em_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
