# Generated by Django 4.1.11 on 2024-11-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0027_alter_project_country_alter_project_em_receive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_guaranty',
            name='bg_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bank_guaranty',
            name='bg_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_target',
            name='sales_target',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='employment_record',
            name='salary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='insurance_detail',
            name='amount',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='liquidity_damages',
            name='max_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='liquidity_damages',
            name='percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='advance_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='advance_tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='earnest_money',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pg_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pg_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
