# Generated by Django 4.1.11 on 2024-11-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_alter_bank_guaranty_bg_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='closing_doc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='closing_remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
