# Generated by Django 4.1.11 on 2024-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0030_alter_project_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pg_instrument_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
