# Generated by Django 4.1.11 on 2024-12-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0031_alter_project_pg_instrument_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
