# Generated by Django 4.2.2 on 2024-12-11 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0032_sales_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.client'),
        ),
        migrations.AddField(
            model_name='leads',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Employee_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_key_acc_mgr', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
            options={
                'db_table': 'employee_project',
            },
        ),
    ]
