# Generated by Django 4.2.2 on 2024-12-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0033_leads_client_leads_title_employee_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_guaranty',
            name='guarantee_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
