# Generated by Django 4.2 on 2025-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_bank_guaranty_guarantee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='expected_end_time',
            field=models.TimeField(blank=True, help_text='Expected end time for the employee', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='expected_start_time',
            field=models.TimeField(blank=True, help_text='Expected start time for the employee', null=True),
        ),
    ]
