# Generated by Django 4.2 on 2025-05-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0035_employee_expected_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issuing_authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('short_name', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'issuing_authority',
            },
        ),
        migrations.AddField(
            model_name='document_type',
            name='purpose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_document',
            name='document_direction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project_document',
            name='received_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Company_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('issuance_date', models.DateField(null=True)),
                ('expire_date', models.DateField(null=True)),
                ('doc_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('issuing_authority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.issuing_authority')),
            ],
            options={
                'db_table': 'company_document',
            },
        ),
        migrations.AddField(
            model_name='project_document',
            name='company_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company_document'),
        ),
    ]
