# Generated by Django 4.2 on 2025-06-04 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0037_company_document_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_document',
            name='company_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.company_document'),
        ),
        migrations.AlterField(
            model_name='project_document',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
