# Generated by Django 4.2 on 2025-06-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0038_alter_project_document_company_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
