# Generated by Django 4.2 on 2025-04-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_attendancerule_payrollworkflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
