# Generated by Django 4.2 on 2025-04-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salarycomponent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollcalculation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrolldocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payrollworkflowstep',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
