# Generated by Django 4.1.11 on 2024-10-31 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0025_project_document_issuance_date_and_more'),
        ('project_initiation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendor',
            name='adpscheme_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tendor',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.client'),
        ),
    ]
