# Generated by Django 4.1.11 on 2024-11-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0002_tendor_adpscheme_no_tendor_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tax',
            },
        ),
    ]
