# Generated by Django 4.1.11 on 2024-11-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0003_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq_items',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.boq_items'),
        ),
        migrations.CreateModel(
            name='Boq_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('tax_amount', models.IntegerField(null=True)),
                ('total_amount', models.IntegerField(null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('tendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.tendor')),
            ],
            options={
                'db_table': 'boq_master',
            },
        ),
        migrations.AddField(
            model_name='boq_items',
            name='boq_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.boq_master'),
        ),
    ]
