# Generated by Django 4.1.11 on 2024-11-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0004_boq_items_parent_boq_master_boq_items_boq_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq_items',
            name='groupid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
