# Generated by Django 4.1.11 on 2024-11-19 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0005_alter_boq_items_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq_items',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Boq_items', to='project_initiation.boq_items'),
        ),
    ]
