# Generated by Django 4.1.11 on 2024-11-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0006_boq_items_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq_items',
            name='conversion_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boq_items',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boq_items',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boq_master',
            name='tax_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='boq_master',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tendor',
            name='bg_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tendor',
            name='em_percentage',
            field=models.FloatField(null=True),
        ),
    ]
