# Generated by Django 4.1.11 on 2024-11-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0007_alter_boq_items_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boq_master',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
