# Generated by Django 4.2.2 on 2024-12-27 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0008_alter_boq_master_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading',
            name='tendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.tendor'),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.unit'),
        ),
        migrations.AlterField(
            model_name='sub_heading',
            name='heading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.heading'),
        ),
        migrations.AlterField(
            model_name='sub_heading',
            name='tendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.tendor'),
        ),
    ]
