# Generated by Django 4.2 on 2025-02-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0034_bank_guaranty_guarantee_type'),
        ('project_initiation', '0009_alter_heading_tendor_alter_item_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iso_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('delivery_date_commeted', models.DateField(blank=True, null=True)),
                ('delivery_date_required', models.DateField(blank=True, null=True)),
                ('payment_term', models.CharField(blank=True, max_length=50, null=True)),
                ('em_percentage', models.FloatField(blank=True, null=True)),
                ('em_amount', models.FloatField(blank=True, null=True)),
                ('bg_percentage', models.FloatField(blank=True, null=True)),
                ('bg_amount', models.FloatField(blank=True, null=True)),
                ('pg_percentage', models.FloatField(blank=True, null=True)),
                ('pg_amount', models.FloatField(blank=True, null=True)),
                ('total_value_iso', models.FloatField(blank=True, null=True)),
                ('total_cost_iso', models.FloatField(blank=True, null=True)),
                ('initial_gp_planned', models.FloatField(blank=True, null=True)),
                ('gp_after_tax', models.FloatField(blank=True, null=True)),
                ('total_sales_promo', models.FloatField(blank=True, null=True)),
                ('final_gp_after_promo', models.FloatField(blank=True, null=True)),
                ('total_financial_charges', models.FloatField(blank=True, null=True)),
                ('initial_gp_percentage', models.FloatField(blank=True, null=True)),
                ('final_gp_percentage', models.FloatField(blank=True, null=True)),
                ('final_gp_after_financial', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_shipment', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_person', models.IntegerField(blank=True, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('delivery_type', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.client')),
                ('tendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.tendor')),
            ],
            options={
                'db_table': 'iso_master',
            },
        ),
        migrations.CreateModel(
            name='Iso_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_percentage', models.FloatField(blank=True, null=True)),
                ('import_factor', models.FloatField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('unit_cost_pkr', models.FloatField(blank=True, null=True)),
                ('total_pkr', models.FloatField(blank=True, null=True)),
                ('gp_calculation', models.FloatField(blank=True, null=True)),
                ('unit_selling_pkr', models.FloatField(blank=True, null=True)),
                ('delivery_charges', models.FloatField(blank=True, null=True)),
                ('total_selling_price', models.FloatField(blank=True, null=True)),
                ('gst_amount', models.FloatField(blank=True, null=True)),
                ('total_with_gst', models.FloatField(blank=True, null=True)),
                ('income_tax_adjustment', models.FloatField(blank=True, null=True)),
                ('gp_percentage', models.FloatField(blank=True, null=True)),
                ('gp_amount', models.FloatField(blank=True, null=True)),
                ('tax_adjusment', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('iso_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.iso_master')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.item')),
                ('sales_tax_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.tax')),
            ],
            options={
                'db_table': 'iso_detail',
            },
        ),
    ]
