# Generated by Django 4.2 on 2025-06-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0010_iso_master_iso_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iso_detail',
            name='unit_cost_pkr',
        ),
        migrations.AddField(
            model_name='iso_detail',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='iso_detail',
            name='currency_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_detail',
            name='unit_cost_exchange_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
