# Generated by Django 4.2 on 2025-06-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0011_remove_iso_detail_unit_cost_pkr_iso_detail_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso_detail',
            old_name='total_pkr',
            new_name='total_with_import',
        ),
        migrations.AddField(
            model_name='iso_detail',
            name='total_without_import',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
