# Generated by Django 4.2 on 2025-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0012_rename_total_pkr_iso_detail_total_with_import_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_markup_percentage', models.FloatField(blank=True, null=True)),
                ('em_fc_ratio', models.FloatField(blank=True, null=True)),
                ('bg_fc_ratio', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'setting',
            },
        ),
        migrations.RenameField(
            model_name='iso_master',
            old_name='delivery_date_commeted',
            new_name='delivery_date_committed',
        ),
        migrations.AddField(
            model_name='iso_master',
            name='advance_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='advance_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='beneficiary_payorder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='bg_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='bg_fc_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='em_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='em_fc_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='fc_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='fc_markup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='iso_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='pg_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='pg_fc_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='sale_promo_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
