# Generated by Django 4.2 on 2025-07-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0014_setting_per_kg_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso_detail',
            name='per_kg_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_detail',
            name='unit_weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
