# Generated by Django 4.2 on 2025-07-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_employee_cnic_back_employee_cnic_front_and_more'),
        ('project_initiation', '0015_iso_detail_per_kg_rate_iso_detail_unit_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iso_detail',
            old_name='income_tax_adjustment',
            new_name='tax_adjusment_amt',
        ),
        migrations.RenameField(
            model_name='iso_master',
            old_name='total_sales_promo',
            new_name='sales_promo',
        ),
        migrations.AddField(
            model_name='iso_detail',
            name='final_amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='iso_master',
            name='total_delivery_charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iso_master',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_employee', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='iso_master',
            name='iso_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='iso_master',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_employee', to='employee.employee'),
        ),
    ]
