# Generated by Django 4.2 on 2025-08-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0017_component_item_maker_item_model_specs_spec_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso_detail',
            name='remarks',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
