# Generated by Django 4.2 on 2025-09-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_employee_cnic_back_employee_cnic_front_and_more'),
        ('project_initiation', '0018_iso_detail_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_quotation_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('tendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_initiation.tendor')),
            ],
            options={
                'db_table': 'vendor_quotation_master',
            },
        ),
        migrations.CreateModel(
            name='Vendor_quotation_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.item')),
                ('item_spec_values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.item_spec_values')),
                ('vendor_quotation_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.vendor_quotation_master')),
            ],
            options={
                'db_table': 'vendor_quotation_detail',
            },
        ),
        migrations.CreateModel(
            name='Quotation_vendor_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('without_tax_amount', models.FloatField(blank=True, null=True)),
                ('with_tax_amount', models.FloatField(blank=True, null=True)),
                ('attached_file', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.vendor')),
                ('vendor_quotation_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_initiation.vendor_quotation_master')),
            ],
            options={
                'db_table': 'quotation_vendor_list',
            },
        ),
    ]
