# Generated by Django 4.2 on 2025-09-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0019_vendor_quotation_master_vendor_quotation_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quotation_detail',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
