# Generated by Django 4.2 on 2025-09-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0020_vendor_quotation_detail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='footer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='header',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
