# Generated by Django 4.2 on 2025-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_initiation', '0021_setting_footer_setting_header_setting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quotation_master',
            name='ref_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
